version: "3.3"

services:
  db:
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: gunicorn library.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
      - ./tests:/app/tests
      - ./data/media:/public/media
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_volume: