# Generated by Django 3.0.4 on 2020-10-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201015_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookauthors_set', to='books.Book'),
        ),
    ]
